/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptException;

/**
 *
 * @author eduardo
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        tela = new javax.swing.JTextField();
        numberfive = new javax.swing.JButton();
        numberone = new javax.swing.JButton();
        numbertwo = new javax.swing.JButton();
        numbertre = new javax.swing.JButton();
        numberfor = new javax.swing.JButton();
        numberseven = new javax.swing.JButton();
        numbersix = new javax.swing.JButton();
        numbereigth = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        numbernine = new javax.swing.JButton();
        sum = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        virgule = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        division = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        virgule1 = new javax.swing.JButton();
        par1 = new javax.swing.JButton();
        par2 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaActionPerformed(evt);
            }
        });

        numberfive.setText("5");
        numberfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberfiveActionPerformed(evt);
            }
        });

        numberone.setText("1");
        numberone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberoneActionPerformed(evt);
            }
        });

        numbertwo.setText("2");
        numbertwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbertwoActionPerformed(evt);
            }
        });

        numbertre.setText("3");
        numbertre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbertreActionPerformed(evt);
            }
        });

        numberfor.setText("4");
        numberfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberforActionPerformed(evt);
            }
        });

        numberseven.setText("7");
        numberseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersevenActionPerformed(evt);
            }
        });

        numbersix.setText("6");
        numbersix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersixActionPerformed(evt);
            }
        });

        numbereigth.setText("8");
        numbereigth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbereigthActionPerformed(evt);
            }
        });

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        numbernine.setText("9");
        numbernine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbernineActionPerformed(evt);
            }
        });

        sum.setText("+");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        virgule.setText(",");
        virgule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virguleActionPerformed(evt);
            }
        });

        mult.setText("*");
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });

        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        calculate.setText("calcular");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        virgule1.setText("del");
        virgule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virgule1ActionPerformed(evt);
            }
        });

        par1.setText("(");
        par1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                par1ActionPerformed(evt);
            }
        });

        par2.setText(")");
        par2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                par2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(numberseven, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(numbereigth, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numbernine, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(par1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(virgule1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(virgule, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numberfor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numberone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(numberfive, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(numbersix, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(numbertwo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(numbertre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(204, 204, 204)
                                    .addComponent(par2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(tela, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sum)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numbertwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberone, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numbertre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(division)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(virgule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(par1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(par2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberfor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberfive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numbersix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(numbernine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numbereigth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numberseven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(virgule1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calculate, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_telaActionPerformed

    private void numberfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberfiveActionPerformed
        // TODO add your handling code here:
     String newvalue =  Draw.drawtela(tela.getText(),numberfive.getText());
     tela.setText(newvalue);
    }//GEN-LAST:event_numberfiveActionPerformed

    private void numberoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberoneActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),numberone.getText());
     tela.setText(newvalue);
        
    }//GEN-LAST:event_numberoneActionPerformed

    private void numbertwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbertwoActionPerformed
         String newvalue =  Draw.drawtela(tela.getText(),numbertwo.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_numbertwoActionPerformed

    private void numbertreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbertreActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),numbertre.getText());
     tela.setText(newvalue);        
// TODO add your handling code here:
    }//GEN-LAST:event_numbertreActionPerformed

    private void numberforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberforActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),numberfor.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_numberforActionPerformed

    private void numbersevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersevenActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),numberseven.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_numbersevenActionPerformed

    private void numbersixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersixActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),numbersix.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_numbersixActionPerformed

    private void numbereigthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbereigthActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),numbereigth.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_numbereigthActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),zero.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:

    }//GEN-LAST:event_zeroActionPerformed

    private void numbernineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbernineActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),numbernine.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_numbernineActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),sub.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_subActionPerformed

    private void virguleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virguleActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),".");
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_virguleActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),mult.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_multActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
     String newvalue =  Draw.drawtela(tela.getText(),division.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_divisionActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
  String newvalue =  Draw.drawtela(tela.getText(),sum.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_sumActionPerformed

    private void virgule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virgule1ActionPerformed
        // TODO add your handling code here:
 String newvalue =  Draw.erasetela(tela.getText());
     tela.setText(newvalue);
    }//GEN-LAST:event_virgule1ActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        String math = null;
        try {
            math = Calculate.math(tela.getText());
        } catch (ScriptException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setText(math);
    }//GEN-LAST:event_calculateActionPerformed

    private void par1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_par1ActionPerformed
       String newvalue =  Draw.drawtela(tela.getText(),par1.getText());
     tela.setText(newvalue);
    }//GEN-LAST:event_par1ActionPerformed

    private void par2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_par2ActionPerformed
       String newvalue =  Draw.drawtela(tela.getText(),par2.getText());
     tela.setText(newvalue);
        // TODO add your handling code here:
    }//GEN-LAST:event_par2ActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          NewJFrame frame;
                frame = new NewJFrame();
                        frame.setVisible(true);
                        frame.setResizable(false);
 }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton division;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton mult;
    private javax.swing.JButton numbereigth;
    private javax.swing.JButton numberfive;
    private javax.swing.JButton numberfor;
    private javax.swing.JButton numbernine;
    private javax.swing.JButton numberone;
    private javax.swing.JButton numberseven;
    private javax.swing.JButton numbersix;
    private javax.swing.JButton numbertre;
    private javax.swing.JButton numbertwo;
    private javax.swing.JButton par1;
    private javax.swing.JButton par2;
    private javax.swing.JButton sub;
    private javax.swing.JButton sum;
    private javax.swing.JTextField tela;
    private javax.swing.JButton virgule;
    private javax.swing.JButton virgule1;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
